### ISSUE TITLE
Universal? 

### ISSUE THREAD

**Issue by cyberelon** [karthik558/Splash-Maker-#2]
This tool is universal right? I can use it to generate splashes for beryllium or any 18*9 devices?

**Comment by LorVC** [comment]
You should change something in the META-INF folder,but the problem is that i don't understand what,one update-binary isn't readable,the other just replaces a file,but idk if we should modify that replace

**Comment by LorVC** [comment]
after few testing i dubt thats the problem,its more related on the size of images

**Comment by karthik558** [comment]
> This tool is universal right? I can use it to generate splashes for beryllium or any 18*9 devices?

dont know try

**Comment by karthik558** [comment]
> after few testing i dubt thats the problem,its more related on the size of images

which device ??

**Comment by LorVC** [comment]
Lavender A10

Il lun 1 feb 2021, 08:43 K A R T H I K <notifications@github.com> ha
scritto:
